defaults:
  - _self_
  - model: od
  - data: od

seed: 3072
embed_dim: 192
history_size: 3
num_preds: 1

loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024

optimizer:
  lr: 5e-5
  weight_decay: 1e-3

trainer:
  max_epochs: 8
  accelerator: auto
  devices: auto
  precision: 32
  gradient_clip_val: 1.0

wandb:
  enabled: true
  config:
    entity: sps-tum
    project: ${oc.env:WANDB_PROJECT,space-world-models}

