_target_: models.od_jepa.ODJEPA

encoder:
  _target_: models.od_encoder.OdEncoder
  in_dim: 4
  hidden_dim: 256
  out_dim: ${embed_dim}

predictor:
  _target_: module.ARPredictor
  num_frames: ${history_size}
  input_dim: ${embed_dim}
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}
  depth: 4
  heads: 8
  mlp_dim: 512
  dim_head: 48
  dropout: 0.1
  emb_dropout: 0.0

action_encoder:
  _target_: module.Embedder
  input_dim: 3
  smoothed_dim: 3
  emb_dim: ${embed_dim}

projector:
  _target_: module.MLP
  input_dim: ${embed_dim}
  hidden_dim: 512
  output_dim: ${embed_dim}
  norm_fn: null

pred_proj:
  _target_: module.MLP
  input_dim: ${embed_dim}
  hidden_dim: 512
  output_dim: ${embed_dim}
  norm_fn: null

