_target_: core.models.vector_jepa.VectorJEPA

encoder:
  _target_: core.models.vector_encoder.VectorEncoder
  in_dim: 25
  hidden_dim: 256
  out_dim: ${embed_dim}

predictor:
  _target_: core.models.components.ARPredictor
  num_frames: ${history_size}
  input_dim: ${embed_dim}
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}
  depth: 4
  heads: 8
  mlp_dim: 512
  dim_head: 48
  dropout: 0.1
  emb_dropout: 0.0

action_encoder:
  _target_: core.models.components.Embedder
  input_dim: 7
  smoothed_dim: 7
  emb_dim: ${embed_dim}

projector:
  _target_: core.models.components.MLP
  input_dim: ${embed_dim}
  hidden_dim: 512
  output_dim: ${embed_dim}
  norm_fn: null

pred_proj:
  _target_: core.models.components.MLP
  input_dim: ${embed_dim}
  hidden_dim: 512
  output_dim: ${embed_dim}
  norm_fn: null
